Disable some sections of this script for VSCHILD class

diff --git a/mugwump/vserver/examples/simple/scripts/LAST/50-misc b/mugwump/vserver/examples/simple/scripts/LAST/50-misc
--- a/mugwump/vserver/examples/simple/scripts/LAST/50-misc
+++ b/mugwump/vserver/examples/simple/scripts/LAST/50-misc
@@ -14,20 +14,27 @@ done
 echo "#$FAI_DEBMIRROR $MNTPOINT nfs ro 0 0" >> $target/etc/fstab
 
 # set bios clock
-if [ $DO_INIT_TASKS -eq 1 ] ; then
-    case "$UTC" in
-       no|"") hwopt="--localtime" ;;
-       yes)   hwopt="--utc"       ;;
-    esac
-    $ROOTCMD hwclock $hwopt --systohc
+if ! ifclass VSCHILD
+then
+    if [ $DO_INIT_TASKS -eq 1 ] ; then
+        case "$UTC" in
+           no|"") hwopt="--localtime" ;;
+           yes)   hwopt="--utc"       ;;
+        esac
+        $ROOTCMD hwclock $hwopt --systohc
+    fi
 fi
 
 # Make sure everything is configured properly
 echo "Running \"apt-get -f install\" for the last time."
 $ROOTCMD apt-get -f install
 
-lskernels=$(echo $target/boot/vmlinu*)
-[ -f ${lskernels%% *} ] || echo "ERROR: No kernel was installed. Have a look at shell.log"
+if ! ifclass VSCHILD
+then
+    lskernels=$(echo $target/boot/vmlinu*)
+    [ -f ${lskernels%% *} ] || echo "ERROR: No kernel was installed. Have a look at shell.log"
+fi
+
 # copy sources.list
 fcopy -i /etc/apt/sources.list
 
