update to fai 3.1, merging ubuntu customisation

diff --git a/siretart/ubuntu/lib/subroutines-linux b/siretart/ubuntu/lib/subroutines-linux
--- a/siretart/ubuntu/lib/subroutines-linux
+++ b/siretart/ubuntu/lib/subroutines-linux
@@ -45,7 +45,7 @@ eval_cmdline() {
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 ### BEGIN SUBROUTINE INFO
-# Provides-Var:    $faimond $sndhostname
+# Provides-Var:    $faimond $sendhostname
 # Requires-Var:    $LOGDIR $FAI
 # Suggests-Var:    $monserver
 # Short-Description: <task desc.>
@@ -81,8 +81,8 @@ task_confdir() {
     # check if monitor server is available
     [ -z "$monserver" ] && monserver=$SERVER
     faimond=1
-    sndhostname=$HOSTNAME # save current hostname
-    if sndmon check; then
+    sendhostname=$HOSTNAME # save current hostname
+    if sendmon check; then
 	echo "Monitoring to server $monserver enabled."
     else
 	faimond=0
@@ -103,7 +103,7 @@ task_partition() {
     # setup_harddisks must create $LOGDIR/disk_var.sh file
     if [ ! -s $LOGDIR/disk_var.sh ]; then
 	cat $LOGDIR/format.log
-	sndmon "TASKERROR partition 21"
+	sendmon "TASKERROR partition 21"
 	die "setup_harddisks did not create $LOGDIR/disk_var.sh file."
     fi
     # now define variable for root and boot partition and boot device
@@ -127,6 +127,7 @@ task_extrbase() {
     [ -d $FAI/basefiles ] && ftar -1v -s $FAI/basefiles /
     if [ $? -ne 0 ]; then
 	[ $do_init_tasks -eq 0 ] && basefile=$NFSROOT/var/tmp/base.tgz
+	[ -f $basefile ] || die "$basefile not found. Can't extract it. Aborting."
 	# extract the tar file which was the result of debootstrap
 	echo "Extracting $NFSROOT/var/tmp/base.tgz"
 	gzip -dc $basefile | tar -C $FAI_ROOT -xpf -
@@ -151,7 +152,7 @@ task_mirror() {
     if mount $romountopt $FAI_DEBMIRROR $FAI_ROOT/$MNTPOINT; then
       [ "$debug" ] && echo "Mirror mounted from $FAI_DEBMIRROR to $FAI_ROOT/$MNTPOINT"
     else
-      sndmon "TASKERROR mirror $?"
+      sendmon "TASKERROR mirror $?"
       die "Can't mount $FAI_DEBMIRROR"
     fi
 }
@@ -193,6 +194,8 @@ APT::Get::AllowUnauthenticated "true";
 Aptitude::CmdLine::Ignore-Trust-Violations yes;
 EOF
     fi
+    # during normal installation, we need sources.list from /etc/apt
+    [ $do_init_tasks -eq 1 ] && FAI_ETC_DIR=/etc
     [ -d $FAI_ETC_DIR/apt ] && cp -r $FAI_ETC_DIR/apt/* $FAI_ROOT/etc/apt/
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
@@ -276,11 +279,11 @@ task_chboot() {
     fi
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
-sndmon() {
+sendmon() {
 
     # send message to monitor daemon
     [ "$faimond" -eq 0 ] && return 0
-    echo "$sndhostname $*" | nc $monserver 4711 2>/dev/null
+    echo "$sendhostname $*" | nc $monserver 4711 2>/dev/null
     return $?
 }
 # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
